server:
  port: 8080
  servlet:
    context-path: /app
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml

spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/punto-red
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
          import_files: 0_create_user.sql
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
settings:
  request:
    url: https://us-central1-puntored-dev.cloudfunctions.net/technicalTest-developer/api
    key: mtrQF6Q11eosqyQnkMY0JGFbGqcxVg5icvfVnX1ifIyWDvwGApJ8WUM8nHVrdSkN
  application:
    name: punto-red
  auth:
    token-time: 30
