server:
  port: 8080
  servlet:
    context-path: /app
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml

spring:
  datasource:
    username: neondb_owner
    password: npg_FLGMpdx2vDo9
    url: jdbc:postgresql://ep-cold-water-ad7mx9n5.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
          import_files: 0_create_user.sql
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
settings:
  request:
    url: https://us-central1-puntored-dev.cloudfunctions.net/technicalTest-developer/api
    key: mtrQF6Q11eosqyQnkMY0JGFbGqcxVg5icvfVnX1ifIyWDvwGApJ8WUM8nHVrdSkN
  application:
    name: punto-red
  auth:
    token-time: 30
